### PR TITLE
Fix image in user guide

### LINKED ISSUE #126: [PE-D][Tester D] Application Ui does not correspond to the UG UI
App:

UG:

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: t1mzzz/ped#2

### LINKED ISSUE #127: [PE-D][Tester B] Name of Application does not match the one mentioned in User Guide
Similar to the previous bug, when I opened the application, the title shown was "Address App". Maybe it is better to match them to prevent user confusion?

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: maryjess/ped#2

### LINKED ISSUE #129: [PE-D][Tester C] Examples of `add -p` command is missing the demarcater `-p`
-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: peppapighs/ped#2

### LINKED ISSUE #135: [PE-D][Tester B] Features Syntax in UG
In this point with regards to the `add -p` command example, when I run the example `add n/PINNACLE@DUXTON` evaluates to an unknown command, but think this is minor as user can figure out how to change the input. Can clarify this better by adding the `-p` tag

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: maryjess/ped#4

### LINKED ISSUE #137: [PE-D][Tester C] Examples of `edit -p` command is missing the demarcater `-p`
-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: peppapighs/ped#4

### LINKED ISSUE #139: [PE-D][Tester C] Format of `find -p` command is missing the demarcater `-p`
-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: peppapighs/ped#5

### LINKED ISSUE #141: [PE-D][Tester E] UG command format for add -p is different from app.
In the UG, there is no mention of needing a h/ for property type.

However, in the app, it returns a invalid command format.

In addition, in the examples, there is no use of add -p, it just uses add. Furthermore, the example also includes the h/ tag for property type.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: therealdaofu/ped#4

### LINKED ISSUE #143: [PE-D][Tester B] Help feature in UG does not show the current link of the UG
The screenshot of the help window is not reflecting the same URL as the current UG URL I am opening right now. But can still get the URL from the app by typing the help command

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: maryjess/ped#7

### LINKED ISSUE #145: [PE-D][Tester E] Inconsistency in UG for edit -p command
Title is editing property, description is for people? I was confused by this.

Command is edit -p but given example used edit.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: therealdaofu/ped#5

### LINKED ISSUE #161: [PE-D][Tester B] Broken image under find feature
Very minor, but i think there is a broken image under find feature?

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: maryjess/ped#13

### LINKED ISSUE #166: [PE-D][Tester A] Invalid example provided for add command in User Guide, missing the `-p`
The examples provided in the user guide do not work, since they are missing the demarcators. 

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: lesterong/ped#6

### PR DESCRIPTION
**Pull request by yuehernkang**
closes #166 
Closes #127 
Closes #126 
Closes #137 
Closes #135 
Closes #129 
Closes #145 
Closes #141 
Closes #143
Closes #139 
Closes #161

### CODE REVIEW

**Comment by yuehernkang** [comment]
closes #127

**Comment by yuehernkang** [comment]
closese #126

**Comment by yuehernkang** [comment]
closes #137

**Comment by yuehernkang** [comment]
closes #135

**Comment by yuehernkang** [comment]
closes #129

**Comment by yuehernkang** [comment]
closes #145

**Comment by yuehernkang** [comment]
closes #141

**Comment by yuehernkang** [comment]
closes #143

**Comment by yuehernkang** [comment]
closes #139

**Review by zacchaeuschok — APPROVED** [review]

**Review by lkwlkww — APPROVED** [review]

**Pull request merged**
