### PR TITLE
Fix formatting error in AddPropertyCommand example

### LINKED ISSUE #130: [PE-D][Tester D] User Guide does not show proper examples of commands
The heading says `add -p`, while the examples do not have the `-p` flag, hence creating an error in the app.

This happens analogously in other commands in the UG (i.e. `find -p`)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: t1mzzz/ped#4

### LINKED ISSUE #134: [PE-D][Tester E] Cannot add new properties
I copied the error message format and it still did not allow me to add the property. I referenced the UG and used their format and still cannot.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: therealdaofu/ped#3

### LINKED ISSUE #168: [PE-D][Tester A] Example provided in `add -p` error message is incorrect, copying it leads to an error
The example provided in `add -p` is incorrect. It results in an error, since it is missing a space. 

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: lesterong/ped#7

### PR DESCRIPTION
**Pull request by yuehernkang**
No spacing in the example 

closes #168 
Closes #134
closes #130
Closes #198

### CODE REVIEW

**Comment by yuehernkang** [comment]
closes #168

**Comment by yuehernkang** [comment]
closes #134

**Comment by yuehernkang** [comment]
closes #130

**Comment by yuehernkang** [comment]
closes #198

**Review by zacchaeuschok — APPROVED** [review]

**Pull request merged**
