### PR TITLE
Change file name output from shadowJar

### LINKED ISSUE #122: [PE-D][Tester D] Jar file not same as the UserGuide
The UG (above) states the filename should be `condonery.jar`, while the release still has the name as `addressbook.jar`:

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: t1mzzz/ped#1

### LINKED ISSUE #124: [PE-D][Tester B] JAR file name doesn't match name stated in User Guide
In the User Guide, the name is stated as "condonery.jar", whereas the jar file that I downloaded, the name was "addressbook.jar"

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: maryjess/ped#1

### LINKED ISSUE #127: [PE-D][Tester B] Name of Application does not match the one mentioned in User Guide
Similar to the previous bug, when I opened the application, the title shown was "Address App". Maybe it is better to match them to prevent user confusion?

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: maryjess/ped#2

### LINKED ISSUE #176: [PE-D][Tester C] Application file name in User Guide is different from the actual release
As shown in the image belows, the file name to download should be `condonery.jar`, although the actual release file name is `addressbook.jar`.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: peppapighs/ped#14

### PR DESCRIPTION
**Pull request by yuehernkang**
ShadowJar generated file names will be `condonery.jar`

Closes #176 
Closes #122 
Closes #127 
Closes #124

### CODE REVIEW

**Comment by yuehernkang** [comment]
closes #176

**Comment by yuehernkang** [comment]
closes #122

**Comment by yuehernkang** [comment]
closes #127

**Comment by yuehernkang** [comment]
closes #127

**Comment by yuehernkang** [comment]
closes #124

**Review by zacchaeuschok — APPROVED** [review]

**Review by lkwlkww — APPROVED** [review]

**Pull request merged**
