### PR TITLE
Update documentation for jekyll site

### LINKED ISSUE #6: Update site-wide settings

### PR DESCRIPTION
**Pull request by lkwlkww**
close #6

### CODE REVIEW

**Review by misterpuffin — COMMENTED** [review]
Thanks for helping set-up the documentation! Just wanted to check - is there any reason why the Gemfiles are being deleted? Not sure if they're being used by the Jekyll site.

Also, noticed that you have a few PR's with overlapping changes! I think you could consider keeping your master branch in your forked directory in sync with the master branch of our team repo, to better track the changes. But not a big issue! will be resolved when we approve the PR.

**Comment by lkwlkww** [comment]
> Thanks for helping set-up the documentation! Just wanted to check - is there any reason why the Gemfiles are being deleted? Not sure if they're being used by the Jekyll site.
> 
> Also, noticed that you have a few PR's with overlapping changes! I think you could consider keeping your master branch in your forked directory in sync with the master branch of our team repo, to better track the changes. But not a big issue! will be resolved when we approve the PR.

Thanks HR! The Gemfiles were originally added by me (not originally existing) because I was trying to set up some local Jekyll stuff. But it didn't work out so I deleted those Gemfiles to make it cleaner.

Yup! I made a mistake by not creating a new branch for a new issue, because I didn't know that only 1 PR can be associated with 1 branch. Will be mindful of this in future, and will check out the syncing too. Thanks!

**Review by yuehernkang — APPROVED** [review]
LGTM

**Review by misterpuffin — APPROVED** [review]
lgtm!

**Pull request merged**
